name: Publish new release
on:
  workflow_dispatch:
    inputs:
      versionName:
        description: "Version Name"
        required: true
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch code
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: "21"
          distribution: "adopt"
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v3
      - name: Build with Gradle
        run: |
          ./gradlew :bifrost-plugin:build
      - name: Publish to Github Package and Gradle Plugin Portal
        run: ./gradlew :bifrost-plugin:publishGprPublicationToGitHubPackagesRepository :bifrost-plugin:publishPlugins -Pgradle.publish.key=${{ secrets.GRADLE_KEY }} -Pgradle.publish.secret=${{ secrets.GRADLE_SECRET }}
        env:
          BIFROST_VERSION: ${{ github.event.inputs.versionName }}
          GPR_USERNAME: ${{ secrets.USERNAME }}
          GPR_TOKEN: ${{ secrets.TOKEN }}
  release:
    runs-on: ubuntu-latest
    needs: [ publish ]
    steps:
      - name: Checkout branch code
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: "21"
          distribution: "adopt"
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v3
      - name: Build with Gradle
        run: |
          ./gradlew :bifrost-plugin:build
      - name: Bump version and push tag
        id: ${{ github.event.inputs.versionName }}
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.TOKEN }}
      - name: Create new release
        uses: ncipollo/release-action@v1
        with:
          name: ${{ github.event.inputs.versionName }}
          tag: ${{ github.event.inputs.versionName }}
          artifacts: "bifrost-plugin/build/libs/*.jar"
          body: "new release"