name: Publish new release
on:
  workflow_dispatch:
    inputs:
      versionName:
        description: "Version Name"
        required: true
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch code
        uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: "21"
          distribution: "adopt"
      - name: Grant Permission to Execute Gradle
        run: chmod +x gradlew
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@ccb4328a959376b642e027874838f60f8e596de3
      - name: Publish to Github Package and Gradle Plugin Portal
        run: ./gradlew :bifrost-plugin:publish -Pgradle.publish.key=${{ secrets.GRADLE_KEY }} -Pgradle.publish.secret=${{ secrets.GRADLE_SECRET }} --no-configuration-cache
        env:
          BIFROST_VERSION: ${{ github.event.inputs.versionName }}
          GPR_USERNAME: ${{ secrets.USERNAME }}
          GPR_TOKEN: ${{ secrets.TOKEN }}
  release:
    runs-on: ubuntu-latest
    needs: [ publish ]
    steps:
      - name: Checkout branch code
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "21"
          distribution: "adopt"
      - name: Grant Permission to Execute Gradle
        run: chmod +x gradlew
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@ccb4328a959376b642e027874838f60f8e596de3
      - name: Build with Gradle
        run: |
          ./gradlew :bifrost-plugin:build
      - name: Create new tag
        run: |
          git tag -a $TAG -m "Release v$TAG"
          git push origin $TAG
        env:
          TAG: ${{ github.event.inputs.versionName }}
      - name: Create new release
        uses: ncipollo/release-action@v1
        with:
          name: ${{ github.event.inputs.versionName }}
          tag: ${{ github.event.inputs.versionName }}
          artifacts: "bifrost-plugin/build/libs/*.jar"
          body: "new release"